apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  labels:
    app: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: reemns97/orders
        ports:
        - containerPort: 80
--- 
apiVersion: v1
kind: Service
metadata:
  name: orders
  labels:
    app: orders
spec:
  selector:
    app: orders
  ports:
    - port: 80
      targetPort: 80 
