apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: payment-resource
spec:
  type: git 
  params:
    - name: revision
      value: dev
    - name: url
      value: https://github.com/Reemns97/level3-project.git
