apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: payment-taskrun
spec:
  serviceAccountName: reem-sa 
  taskRef:
    name: payment
  params:
  - name: IMAGE
    value: "reemns97/payment"
  resources:
    inputs:
    - name: level3-project
      resourceRef:
        name: payment-resource 
