apiVersion: v1
kind: ServiceAccount
metadata:
  name: reem-sa
secrets:
  - name: reem-docker-hub-creds
---

apiVersion: v1
kind: Secret
metadata: 
  name: reem-docker-hub-creds
  annotations:
    tekton.dev/docker-0: https://index.docker.io/v1/
type: kubernetes.io/basic-auth
stringData:
  username: reemns97 
  password: 51d0b315-aa4a-4fe3-9bd6-06fa1d337dc1
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role
subjects:
- kind: ServiceAccount
  name: reem-sa
