apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: shipping-taskrun
spec:
  serviceAccountName: reem-sa 
  taskRef:
    name: shipping
  params:
  - name: IMAGE
    value: "reemns97/shipping"
  resources:
    inputs:
    - name: level3-project
      resourceRef:
        name: shipping-resource
