apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts
  labels:
    app: carts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carts
  template:
    metadata:
      labels:
        app: carts
    spec:
      containers:
      - name: carts
        image: reemns97/carts
        ports:
        - containerPort: 80
--- 
apiVersion: v1
kind: Service
metadata:
  name: carts
  labels:
    app: carts
spec:
  selector:
    app: carts
  ports:
    - port: 80
      targetPort: 80 
