apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: carts-taskrun
spec:
  serviceAccountName: reem-sa 
  taskRef:
    name: carts
  params:
  - name: IMAGE
    value: "reemns97/carts"
  resources:
    inputs:
    - name: level3-project
      resourceRef:
        name: carts-resource 
