apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: e2e-js-test-resource
spec:
  type: git
  params:
    - name: revision
      value: WIP
    - name: url
      value: https://github.com/reemns97/level3-Project.git 
