apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: testrun
spec:
  taskRef:
    name: run-e2e-test-task
  resources:
    inputs:
      - name: level3-project
        resourceRef:
          name: e2e-js-test-resource
