apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: catalogue-taskrun
spec:
  serviceAccountName: reem-sa 
  taskRef:
    name: catalogue
  params:
  - name: IMAGE
    value: "reemns97/catalogue"
  resources:
    inputs:
    - name: level3-project
      resourceRef:
        name: catalogue-resource 
