apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: e2e-test-taskrun
spec:
  serviceAccountName: reem-sa 
  taskRef:
    name: e2e-test
  params:
  - name: IMAGE
    value: "reemns97/e2e-test"
  resources:
    inputs:
    - name: level3-project
      resourceRef:
        name: e2e-test-resource
